### ISSUE TITLE
Do you guys crash into react-parcel-example/index.js: Cannot read property 'start' of undefined ? 

### ISSUE THREAD

**Issue by Obooman** [reicheltp/parcel-react-example#1]
with `parcel build index.html` causing an error.

```bash
🚨  /Volumes/Documents/github/react-parcel-example/index.js: Cannot read property 'start' of undefined
    at module.exports (/Users/oboo_chin/.nvm/versions/node/v8.3.0/lib/node_modules/parcel-bundler/node_modules/babel-to-estree/babylon-to-espree/attachComments.js:56:41)
    at module.exports (/Users/oboo_chin/.nvm/versions/node/v8.3.0/lib/node_modules/parcel-bundler/node_modules/babel-to-estree/babylon-to-espree/index.js:35:3)
    at exports.toEstree (/Users/oboo_chin/.nvm/versions/node/v8.3.0/lib/node_modules/parcel-bundler/node_modules/babel-to-estree/index.js:9:3)
    at module.exports (/Users/oboo_chin/.nvm/versions/node/v8.3.0/lib/node_modules/parcel-bundler/src/transforms/uglify.js:10:39)
    at <anonymous>
```

**Comment by Obooman** [comment]
[#8](https://github.com/parcel-bundler/parcel/issues/8) WOW,here it is.
`parcel build index.html --no-minify` fix this.
